---
base_packages:
  # System utilities
  - less
  - tree
  - wget
  - zip
  - unzip
  - man-db
  - rsync
  - ripgrep   # grep alternative
  - fd        # find alternative
  - bat       # cat alternative
  - duf       # disk usage alternative
  - eza       # ls alternative
  - hyperfine # benchmark
  - ncdu      # disk usage analyzer
  - kitty     # terminal

  # Development utilities
  - vim
  - git
  - git-delta
  - base-devel
  - jq
  - glow       # markdown viewer
  - tokei      # code statistics

  # Networking utilities
  - net-tools
  - iputils
  - traceroute
  - dnsutils
  - nmap
  - bluetui    # Bluetooth TUI manager

  # Security utilities
  - sudo
  - ufw
  - openssh
  - fail2ban
