---
base_packages:
  # System utilities
  - less
  - tree
  - wget
  - zip
  - unzip
  - man-db
  - ripgrep
  - fd
  - bat
  - duf
  - rsync

  # Development utilities
  - vim
  - git
  - git-delta
  - base-devel
  - jq

  # Networking utilities
  - net-tools
  - iputils
  - traceroute
  - dnsutils
  - nmap

  # Security utilities
  - sudo
  - ufw
  - openssh
  - fail2ban
