---
base_packages:
  - git
  - wget
  - openssh
  - sudo
  - ufw
  - fail2ban
  - base-devel
  - zip
  - unzip
  - jq
  - ripgrep
  - fd
  - iputils
  - traceroute
  - rsync
  - vim
