---
- name: Deploy "baikal"
  hosts: all
  become: no

  vars:
    current_user: "{{ ansible_user_id }}"
    baikal_image: ckulka/baikal:nginx
    baikal_address: "{{ internal_bind_address }}"
    baikal_port: 5001
    baikal_dir: /opt/baikal
    baikal_config_dir: /opt/baikal/config

  vars_prompt:
    - name: baikal_specific_dir
      prompt: "Enter Baikal's saved data folder path"
      default: /srv/baikal
      private: no

  tasks:
    - name: Get user UID
      ansible.builtin.getent:
        database: passwd
        key: "{{ current_user }}"
      register: user_info

    - name: Set user UID and GID
      ansible.builtin.set_fact:
        uid: "{{ user_info.ansible_facts.getent_passwd[current_user][1] }}"
        gid: "{{ user_info.ansible_facts.getent_passwd[current_user][2] }}"

    - name: Ensure project directory exists
      become: yes
      ansible.builtin.file:
        path: "{{ baikal_dir }}"
        state: directory
        mode: "0755"
        owner: "{{ current_user }}"
        group: "{{ current_user }}"

    - name: Ensure config directory exists
      become: yes
      ansible.builtin.file:
        path: "{{ baikal_config_dir }}"
        state: directory
        mode: "0755"
        owner: "{{ current_user }}"
        group: "{{ current_user }}"

    - name: Ensure saved data directory exists
      become: yes
      ansible.builtin.file:
        path: "{{ baikal_specific_dir }}"
        state: directory
        mode: "0755"
        owner: "{{ current_user }}"
        group: "{{ current_user }}"

    - name: Write the compose.yml
      ansible.builtin.copy:
        dest: "{{ baikal_dir }}/compose.yml"
        mode: "0644"
        content: |
          services:
            baikal:
              image: "{{ baikal_image }}"
              container_name: baikal
              ports:
                - "{{ baikal_address }}:{{ baikal_port }}:80"
              volumes:
                - {{ baikal_config_dir }}:/var/www/baikal/config
                - {{ baikal_specific_dir }}:/var/www/baikal/Specific
              restart: unless-stopped

    - name: Deploy the service
      community.docker.docker_compose_v2:
        project_src: "{{ baikal_dir }}"
        files:
          - compose.yml
        state: present
        pull: always
