---
- name: Configure Bash
  hosts: all
  become: no

  vars:
    current_user: "{{ ansible_facts['user_id'] }}"

  tasks:
    - name: Copy .bashrc to the user's home
      copy:
        src: "{{ playbook_dir }}/../../Alex/.bashrc"
        dest: "{{ ansible_env.HOME }}/.bashrc"
        owner: "{{ current_user }}"
        group: "{{ current_user }}"
        mode: '0644'
