---
- name: Configure Git
  hosts: all
  become: no

  vars:
    current_user: "{{ ansible_facts['user_id'] }}"

  tasks:
    - name: Copy .gitconfig to user home directory
      copy:
        src: "{{ playbook_dir }}/../../Alex/.gitconfig"
        dest: "{{ ansible_env.HOME }}/.gitconfig"
        owner: "{{ current_user }}"
        group: "{{ current_user }}"
        mode: '0644'
