---
- name: Deploy "linkding"
  hosts: all
  become: no

  vars:
    current_user: "{{ ansible_user_id }}"
    linkding_image: sissbruecker/linkding:latest
    linkding_port: 9090
    linkding_dir: /opt/linkding
    linkding_data_dir: /opt/linkding/data

  vars_prompt:
    - name: linkding_username
      prompt: "Enter username for linkding superuser"
      private: no

    - name: linkding_password
      prompt: "Enter password for linkding superuser"
      private: yes
      confirm: yes

  tasks:
    - name: Ensure project directory exists
      become: yes
      ansible.builtin.file:
        path: "{{ linkding_dir }}"
        state: directory
        mode: "0755"
        owner: "{{ current_user }}"
        group: "{{ current_user }}"

    - name: Ensure config directory exists
      become: yes
      ansible.builtin.file:
        path: "{{ linkding_data_dir }}"
        state: directory
        mode: "0755"
        owner: "{{ current_user }}"
        group: "{{ current_user }}"

    - name: Write the compose.yml
      ansible.builtin.copy:
        dest: "{{ linkding_dir }}/compose.yml"
        mode: "0644"
        content: |
          services:
            linkding:
              image: "{{ linkding_image }}"
              container_name: linkding
              ports:
                - "{{ linkding_port }}:9090"
              volumes:
                - {{ linkding_data_dir }}:/etc/linkding/data
              environment:
                - LD_DISABLE_BACKGROUND_TASKS=False             # Disables background tasks like creating snapshots for bookmarks on Internet Archive
                - LD_DISABLE_URL_VALIDATION=False               # Disables URL validation for bookmarks (i.e. non-FQDN URLs or non-http/https)
                - LD_SUPERUSER_NAME={{ linkding_username }}
                - LD_SUPERUSER_PASSWORD={{ linkding_password }}
              restart: unless-stopped

    - name: Deploy the service
      community.docker.docker_compose_v2:
        project_src: "{{ linkding_dir }}"
        files:
          - compose.yml
        state: present
        pull: always
