---
- name: Bootstrap the services
  hosts: all
  become: no

  tasks:
    - name: Ensure that the services directory exists
      ansible.builtin.file:
        path: "/opt"
        state: directory
        mode: "0755"
