---
- name: Deploy "uptime-kuma"
  hosts: all
  become: no

  vars:
    current_user: "{{ ansible_facts['user_id'] }}"
    uptime_kuma_image: louislam/uptime-kuma:1
    uptime_kuma_port: 3001
    uptime_kuma_dir: /opt/uptime-kuma
    uptime_kuma_data_dir: /opt/uptime-kuma/data

  tasks:
    - name: Ensure project directory exists
      become: yes
      ansible.builtin.file:
        path: "{{ uptime_kuma_dir }}"
        state: directory
        mode: "0755"
        owner: "{{ current_user }}"
        group: "{{ current_user }}"

    - name: Ensure config directory exists
      become: yes
      ansible.builtin.file:
        path: "{{ uptime_kuma_data_dir }}"
        state: directory
        mode: "0755"
        owner: "{{ current_user }}"
        group: "{{ current_user }}"

    - name: Write the compose.yml
      ansible.builtin.copy:
        dest: "{{ uptime_kuma_dir }}/compose.yml"
        mode: "0644"
        content: |
          services:
            uptime-kuma:
              image: "{{ uptime_kuma_image }}"
              container_name: uptime-kuma
              ports:
                - "{{ uptime_kuma_port }}:3001"
              volumes:
                - /var/run/docker.sock:/var/run/docker.sock:ro
                - {{ uptime_kuma_data_dir }}:/app/data
              restart: unless-stopped

    - name: Deploy the service
      community.docker.docker_compose_v2:
        project_src: "{{ uptime_kuma_dir }}"
        files:
          - compose.yml
        state: present
        pull: always
