---
- name: Deploy "watchyourlan"
  hosts: all
  become: no

  vars:
    current_user: "{{ ansible_user_id }}"
    watchyourlan_image: aceberg/watchyourlan:latest
    watchyourlan_address: 0.0.0.0
    watchyourlan_port: 8840
    watchyourlan_dir: /opt/watchyourlan
    watchyourlan_data_dir: /opt/watchyourlan/data
    watchyourlan_timezone: "{{ ansible_date_time.tz }}"
    watchyourlan_interface: "{{ ansible_default_ipv4.interface | default('eth0') }}"

  tasks:
    - name: Ensure project directory exists
      become: yes
      ansible.builtin.file:
        path: "{{ watchyourlan_dir }}"
        state: directory
        mode: "0755"
        owner: "{{ current_user }}"
        group: "{{ current_user }}"

    - name: Ensure config directory exists
      become: yes
      ansible.builtin.file:
        path: "{{ watchyourlan_data_dir }}"
        state: directory
        mode: "0755"
        owner: "{{ current_user }}"
        group: "{{ current_user }}"

    - name: Write the compose.yml
      ansible.builtin.copy:
        dest: "{{ watchyourlan_dir }}/compose.yml"
        mode: "0644"
        content: |
          services:
            watchyourlan:
              image: "{{ watchyourlan_image }}"
              container_name: watchyourlan
              volumes:
                - {{ watchyourlan_data_dir }}:/data/WatchYourLAN
              environment:
                - TZ={{ watchyourlan_timezone }}
                - IFACES={{ watchyourlan_interface }}
                - HOST={{ watchyourlan_address }}
                - PORT={{ watchyourlan_port }}
                - THEME=lumen
                - COLOR=dark
              network_mode: host
              restart: unless-stopped
              privileged: true

    - name: Deploy the service
      community.docker.docker_compose_v2:
        project_src: "{{ watchyourlan_dir }}"
        files:
          - compose.yml
        state: present
        pull: always
